FROM jupyter/base-notebook

USER root

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update && \
    apt-get install -y curl gettext-base

USER jovyan

COPY configs/jupyter_server_config.py /opt/

EXPOSE 8888

CMD ["/bin/bash", "-c", "envsubst < /opt/jupyter_server_config.py > /home/jovyan/.jupyter/jupyter_server_config.py && start-notebook.sh"]