name: Build and Deploy Jupyterlab container
on:
  push:
    paths:
      - dockerfiles/jupyterlab/**
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and Deploy container
        uses: docker/build-push-action@v4
        with:
          context: dockerfiles/jupyterlab
          push: true
          tags: dataplatformlab/jupyterlab
